### ISSUE TITLE
mdsvex layout rendered, missing a _

### ISSUE THREAD

**Issue by SawyerClick** [connorrothschild/.com#47]
🤠 howdy! 🤠  

## ISSUE
I was digging around the source code and found a small issue with your mdsvex layouts being rendered on the live site ([ex here](https://www.connorrothschild.com/post/layout)). 

## FIX
To avoid this, prepend the files with an underscore + make the change in your mdsvex config file

_p.s. dope site dude!_

**Comment by connorrothschild** [comment]
good catch and thanks for flagging! should have just been fixed in 4a0fb11b55e0d378c6fa0d9d1c505f593ed2da2d

hope you are doing well - happy holidays 🙂
